import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BackgroundGradient from "@/components/BackgroundGradient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`relative ${inter.className} bg-app-blue-900 text-white overflow-hidden`}
      >
        {children}
        <BackgroundGradient
          level={1}
          className="absolute bottom-0 -z-10 overflow-visible animate-move-horizontally"
        />
        <BackgroundGradient
          level={2}
          className="absolute -bottom-32 -z-10 overflow-visible"
        />
        <BackgroundGradient
          level={3}
          className="absolute bottom-0 -z-10 overflow-visible animate-move-vertically"
        />
      </body>
    </html>
  );
}
